import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:intl/intl.dart';
import '../../core/constants.dart';
import '../../services/supabase_service.dart';
import '../../models/tutor_model.dart';
import '../../models/subject_model.dart';
import '../../models/availability_model.dart';
import '../../models/booking_model.dart';

class BookingScreen extends StatefulWidget {
  final TutorModel tutor;
  const BookingScreen({super.key, required this.tutor});

  @override
  State<BookingScreen> createState() => _BookingScreenState();
}

class _BookingScreenState extends State<BookingScreen> {
  SubjectModel? _selectedSubject;
  DateTime _selectedDate = DateTime.now().add(const Duration(days: 1));
  AvailabilityModel? _selectedSlot;
  List<AvailabilityModel> _slots = [];
  bool _isLoadingSlots = false;
  final _nameController = TextEditingController();
  final _phoneController = TextEditingController();
  final _notesController = TextEditingController();

  @override
  void initState() {
    super.initState();
    _loadInitialData();
  }

  void _loadInitialData() async {
    final service = context.read<SupabaseService>();
    final profile = await service.getProfile(service.currentUser!.id);
    if (profile != null) {
      _nameController.text = profile.fullName;
    }
    _loadSlots();
  }

  void _loadSlots() async {
    setState(() => _isLoadingSlots = true);
    final service = context.read<SupabaseService>();
    final slots = await service.getTutorAvailability(widget.tutor.id);
    if (mounted) {
      setState(() {
        _slots = slots;
        _isLoadingSlots = false;
      });
    }
  }

  void _bookClass() async {
    if (_selectedSubject == null || _selectedSlot == null) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Please select subject and time slot')),
      );
      return;
    }

    if (_nameController.text.isEmpty || _phoneController.text.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Please provide your name and phone number')),
      );
      return;
    }

    try {
      final service = context.read<SupabaseService>();
      final booking = BookingModel(
        id: '', // Generated by DB
        studentId: service.currentUser!.id,
        tutorId: widget.tutor.id,
        subjectId: _selectedSubject!.id,
        bookingDate: _selectedDate,
        startTime: _selectedSlot!.startTime,
        endTime: _selectedSlot!.endTime,
        status: 'pending',
        totalPrice: widget.tutor.hourlyRate,
        studentName: _nameController.text,
        studentPhone: _phoneController.text,
        notes: _notesController.text,
      );

      debugPrint('Attempting to create booking for tutor: ${widget.tutor.id}');
      await service.createBooking(booking);
      debugPrint('Booking created successfully in Supabase!');
      
      if (mounted) {
        showDialog(
          context: context,
          builder: (context) => AlertDialog(
            title: const Text('Success'),
            content: const Text('Your class booking request has been sent!'),
            actions: [
              TextButton(
                onPressed: () {
                  Navigator.pop(context);
                  Navigator.pop(context);
                },
                child: const Text('OK'),
              ),
            ],
          ),
        );
      }
    } catch (e) {
      debugPrint('CRITICAL: Booking Creation Failed: $e');
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Booking Failed: $e'), backgroundColor: Colors.red),
        );
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Book a Class')),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(24.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            const Text('Select Subject', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 16)),
            const SizedBox(height: 12),
            DropdownButtonFormField<SubjectModel>(
              value: _selectedSubject,
              items: widget.tutor.subjects
                  .map((s) => DropdownMenuItem(value: s, child: Text(s.name)))
                  .toList(),
              onChanged: (v) => setState(() => _selectedSubject = v),
              decoration: const InputDecoration(border: OutlineInputBorder()),
            ),
            const SizedBox(height: 24),
            const Text('Personal Information', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 16)),
            const SizedBox(height: 12),
            TextField(
              controller: _nameController,
              decoration: const InputDecoration(
                hintText: 'Your Full Name',
                prefixIcon: Icon(Icons.person_outline),
              ),
            ),
            const SizedBox(height: 12),
            TextField(
              controller: _phoneController,
              decoration: const InputDecoration(
                hintText: 'Phone Number',
                prefixIcon: Icon(Icons.phone_outlined),
              ),
              keyboardType: TextInputType.phone,
            ),
            const SizedBox(height: 12),
            TextField(
              controller: _notesController,
              decoration: const InputDecoration(
                hintText: 'Special Notes (Optional)',
                prefixIcon: Icon(Icons.note_alt_outlined),
              ),
              maxLines: 2,
            ),
            const SizedBox(height: 24),
            const Text('Select Date', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 16)),
            const SizedBox(height: 12),
            InkWell(
              onTap: () async {
                final date = await showDatePicker(
                  context: context,
                  initialDate: _selectedDate,
                  firstDate: DateTime.now(),
                  lastDate: DateTime.now().add(const Duration(days: 30)),
                );
                if (date != null) setState(() => _selectedDate = date);
              },
              child: Container(
                padding: const EdgeInsets.all(16),
                decoration: BoxDecoration(
                  border: Border.all(color: Colors.grey),
                  borderRadius: BorderRadius.circular(12),
                ),
                child: Row(
                  children: [
                    const Icon(Icons.calendar_today),
                    const SizedBox(width: 12),
                    Text(DateFormat('EEE, MMM d, yyyy').format(_selectedDate)),
                  ],
                ),
              ),
            ),
            const SizedBox(height: 24),
            const Text('Available Time Slots', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 16)),
            const SizedBox(height: 12),
            _isLoadingSlots
                ? const Center(child: CircularProgressIndicator())
                : _slots.isEmpty
                    ? const Text('No slots available for this tutor.')
                    : Wrap(
                        spacing: 8,
                        children: _slots.map((slot) {
                          final isSelected = _selectedSlot == slot;
                          return ChoiceChip(
                            label: Text('${slot.startTime} - ${slot.endTime}'),
                            selected: isSelected,
                            onSelected: (selected) {
                              setState(() => _selectedSlot = selected ? slot : null);
                            },
                          );
                        }).toList(),
                      ),
            const SizedBox(height: 24),
            Container(
              padding: const EdgeInsets.all(16),
              decoration: BoxDecoration(
                color: AppColors.secondaryBackground.withOpacity(0.3),
                borderRadius: BorderRadius.circular(12),
                border: Border.all(color: AppColors.primary.withOpacity(0.2)),
              ),
              child: Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
                  const Text(
                    'Total Fee:',
                    style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
                  ),
                  Text(
                    '\$${widget.tutor.hourlyRate.toStringAsFixed(2)}',
                    style: const TextStyle(
                      fontSize: 20,
                      fontWeight: FontWeight.bold,
                      color: AppColors.primary,
                    ),
                  ),
                ],
              ),
            ),
            const SizedBox(height: 40),
            ElevatedButton(
              onPressed: _bookClass,
              child: const Text('Send Booking Request'),
            ),
          ],
        ),
      ),
    );
  }
}
