import 'package:flutter_lucide/flutter_lucide.dart';
import 'package:henox/controller/my_controller.dart';
import 'package:remixicon/remixicon.dart';

class IconsController extends MyController {
  List lucideIcons =[
    {"icon": LucideIcons.house, "name": "House"},
    {"icon": LucideIcons.a_arrow_down, "name": "a-arrow-down"},
    {"icon": LucideIcons.a_arrow_up, "name": "a-a-arrow-up-down"},
    {"icon": LucideIcons.a_large_small, "name": "a-large-small"},
    {"icon": LucideIcons.activity, "name": "activity"},
    {"icon": LucideIcons.air_vent, "name": "air_vent"},
    {"icon": LucideIcons.accessibility, "name": "accessibility"},
    {"icon": LucideIcons.airplay, "name": "airplay"},
    {"icon": LucideIcons.person_standing, "name": "person_standing"},
    {"icon": LucideIcons.user, "name": "user"},
    {"icon": LucideIcons.user_check, "name": "user_check"},
    {"icon": LucideIcons.user_cog, "name": "user_cog"},
    {"icon": LucideIcons.user_minus, "name": "user_minus"},
    {"icon": LucideIcons.user_pen, "name": "user_pen"},
    {"icon": LucideIcons.user_round, "name": "user_round"},
    {"icon": LucideIcons.user_round_check, "name": "user_round_check"},
    {"icon": LucideIcons.user_round_minus, "name": "user_round_minus"},
    {"icon": LucideIcons.user_round_plus, "name": "user_round_plus"},
    {"icon": LucideIcons.arrows_up_from_line, "name": "arrows_up_from_line"},
    {"icon": LucideIcons.arrow_up_z_a, "name": "arrow_up_z_a"},
    {"icon": LucideIcons.drafting_compass, "name": "drafting_compass"},
    {"icon": LucideIcons.arrow_up_wide_narrow, "name": "arrow_up_wide_narrow"},
    {"icon": LucideIcons.download, "name": "download"},
    {"icon": LucideIcons.ambulance, "name": "ambulance"},
    {"icon": LucideIcons.angry, "name": "angry"},
    {"icon": LucideIcons.annoyed, "name": "annoyed"},
    {"icon": LucideIcons.biceps_flexed, "name": "biceps_flexed"},
    {"icon": LucideIcons.frown, "name": "frown"},
    {"icon": LucideIcons.hand_helping, "name": "hand_helping"},
    {"icon": LucideIcons.hand_metal, "name": "hand_metal"},
    {"icon": LucideIcons.heart, "name": "heart"},
    {"icon": LucideIcons.heart_crack, "name": "heart_crack"},
  ];

  List remixIcons = [
    {"icon": Remix.alert_fill, "name": "alert_fill"},
    {"icon": Remix.account_box_fill, "name": "account_box_fill"},
    {"icon": Remix.add_box_fill, "name": "add_box_fill"},
    {"icon": Remix.arrow_up_circle_fill, "name": "arrow_up_circle_fill"},
    {"icon": Remix.arrow_up_fill, "name": "arrow_up_fill"},
    {"icon": Remix.arrow_down_fill, "name": "arrow_down_fill"},
    {"icon": Remix.arrow_right_fill, "name": "arrow_right_fill"},
    {"icon": Remix.arrow_left_fill, "name": "arrow_left_fill"},
    {"icon": Remix.home_fill, "name": "home_fill"},
    {"icon": Remix.home_office_fill, "name": "home_office_fill"},
    {"icon": Remix.building_fill, "name": "building_fill"},
    {"icon": Remix.store_fill, "name": "store_fill"},
    {"icon": Remix.bank_fill, "name": "bank_fill"},
    {"icon": Remix.hospital_fill, "name": "hospital_fill"},
    {"icon": Remix.tent_fill, "name": "tent_fill"},
    {"icon": Remix.school_fill, "name": "school_fill"},
    {"icon": Remix.government_fill, "name": "government_fill"},
    {"icon": Remix.tent_fill, "name": "tent_fill"},
    {"icon": Remix.mail_fill, "name": "mail_fill"},
    {"icon": Remix.mail_unread_fill, "name": "mail_unread_fill"},
    {"icon": Remix.mail_add_fill, "name": "mail_add_fill"},
    {"icon": Remix.mail_check_fill, "name": "mail_check_fill"},
    {"icon": Remix.mail_close_fill, "name": "mail_close_fill"},
    {"icon": Remix.mail_download_fill, "name": "mail_download_fill"},
    {"icon": Remix.mail_forbid_fill, "name": "mail_forbid_fill"},
    {"icon": Remix.mail_lock_fill, "name": "mail_lock_fill"},
    {"icon": Remix.mail_settings_fill, "name": "mail_settings_fill"},
    {"icon": Remix.mail_star_fill, "name": "mail_star_fill"},
    {"icon": Remix.mail_volume_fill, "name": "mail_volume_fill"},
    {"icon": Remix.inbox_fill, "name": "inbox_fill"},
    {"icon": Remix.inbox_archive_fill, "name": "inbox_archive_fill"},
    {"icon": Remix.inbox_unarchive_fill, "name": "inbox_unarchive_fill"},
  ];
}
