class Event {
  final String id;
  final String title;
  final String description;
  final String location;
  final DateTime date;
  final String imageUrl;
  final double price;
  final String category;
  final String organizer;

  Event({
    required this.id,
    required this.title,
    required this.description,
    required this.location,
    required this.date,
    required this.imageUrl,
    required this.price,
    required this.category,
    required this.organizer,
  });
}

final List<Event> mockEvents = [
  Event(
    id: '1',
    title: 'Neon Summer Festival',
    description: 'Experience the most vibrant music festival of the summer with international DJs and stunning light shows.',
    location: 'Central Park, NY',
    date: DateTime.now().add(const Duration(days: 10)),
    imageUrl: 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=800&q=80',
    price: 49.99,
    category: 'Music',
    organizer: 'Vibe Nation',
  ),
  Event(
    id: '2',
    title: 'Tech Innovators Summit',
    description: 'Join the brightest minds in tech for a day of inspiration, networking, and groundbreaking announcements.',
    location: 'Silicon Valley, CA',
    date: DateTime.now().add(const Duration(days: 15)),
    imageUrl: 'https://images.unsplash.com/photo-1505373630103-7d069c17d1f8?w=800&q=80',
    price: 199.00,
    category: 'Technology',
    organizer: 'Tech Hub',
  ),
  Event(
    id: '3',
    title: 'Artisan Food & Wine Expo',
    description: 'A gourmet experience featuring the finest local wines and handcrafted delicacies from top chefs.',
    location: 'Napa Valley, CA',
    date: DateTime.now().add(const Duration(days: 5)),
    imageUrl: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=800&q=80',
    price: 75.00,
    category: 'Food',
    organizer: 'Gourmet Events',
  ),
  Event(
    id: '4',
    title: 'Starlight Outdoor Cinema',
    description: 'Enjoy classic movies under the stars with premium popcorn and comfortable lounge seating.',
    location: 'Santa Monica, CA',
    date: DateTime.now().add(const Duration(days: 2)),
    imageUrl: 'https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=800&q=80',
    price: 15.00,
    category: 'Movie',
    organizer: 'Moonlight Movies',
  ),
  Event(
    id: '5',
    title: 'Global Jazz Night',
    description: 'An evening of smooth jazz featuring world-renowned saxophonists and jazz ensembles.',
    location: 'Blue Note, NY',
    date: DateTime.now().add(const Duration(days: 7)),
    imageUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=800&q=80',
    price: 35.00,
    category: 'Music',
    organizer: 'Jazz Society',
  ),
  Event(
    id: '6',
    title: 'Future of AI Workshop',
    description: 'Hands-on workshop on building and deploying machine learning models in the real world.',
    location: 'Austin, TX',
    date: DateTime.now().add(const Duration(days: 20)),
    imageUrl: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=800&q=80',
    price: 120.00,
    category: 'Technology',
    organizer: 'AI Labs',
  ),
  Event(
    id: '7',
    title: 'Mastering Italian Cuisine',
    description: 'Learn the secrets of authentic pasta and risotto from master chefs from Tuscany.',
    location: 'Cooking Studio, FL',
    date: DateTime.now().add(const Duration(days: 3)),
    imageUrl: 'https://images.unsplash.com/photo-1498579150354-977475b7ea0b?w=800&q=80',
    price: 90.00,
    category: 'Food',
    organizer: 'Chef Aleesha',
  ),
  Event(
    id: '8',
    title: 'Modern Art Exhibition',
    description: 'Explore the latest works from emerging contemporary artists in this month-long showcase.',
    location: 'Guggenheim, NY',
    date: DateTime.now().add(const Duration(days: 12)),
    imageUrl: 'https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?w=800&q=80',
    price: 25.00,
    category: 'Art',
    organizer: 'City Arts',
  ),
  Event(
    id: '9',
    title: 'Charity Marathon 2024',
    description: 'Run for a cause! Join thousands of participants in this annual city marathon.',
    location: 'Brooklyn Bridge, NY',
    date: DateTime.now().add(const Duration(days: 30)),
    imageUrl: 'https://images.unsplash.com/photo-1530549387634-7547c6a56ca8?w=800&q=80',
    price: 10.00,
    category: 'Sports',
    organizer: 'Health First',
  ),
  Event(
    id: '10',
    title: 'Electronic Dance Carnival',
    description: 'A massive celebration of EDM with top-tier production and high-energy performances.',
    location: 'Miami Beach, FL',
    date: DateTime.now().add(const Duration(days: 25)),
    imageUrl: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=800&q=80',
    price: 85.00,
    category: 'Party',
    organizer: 'EDC Crew',
  ),
  Event(
    id: '11',
    title: 'Indie Rock Showcase',
    description: 'Discover the next big thing in indie rock with a lineup of local breakout bands.',
    location: 'The Garage, WA',
    date: DateTime.now().add(const Duration(days: 8)),
    imageUrl: 'https://images.unsplash.com/photo-1459749411177-042180ce673c?w=800&q=80',
    price: 20.00,
    category: 'Music',
    organizer: 'Indie Sound',
  ),
  Event(
    id: '12',
    title: 'Coffee Roasting Masterclass',
    description: 'From bean to cup: learn the intricate art of roasting and brewing the perfect coffee.',
    location: 'Roastery Lab, OR',
    date: DateTime.now().add(const Duration(days: 4)),
    imageUrl: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&q=80',
    price: 45.00,
    category: 'Food',
    organizer: 'Coffee Culture',
  ),
  Event(
    id: '13',
    title: 'VR Gaming Tournament',
    description: 'Compete in the ultimate virtual reality battle for a chance to win amazing tech prizes.',
    location: 'Game Zone, CA',
    date: DateTime.now().add(const Duration(days: 18)),
    imageUrl: 'https://images.unsplash.com/photo-1592478411213-6153e4ebc07d?w=800&q=80',
    price: 30.00,
    category: 'Technology',
    organizer: 'Play VR',
  ),
  Event(
    id: '14',
    title: 'Photography Workshop',
    description: 'Improve your landscape and portrait photography with guidance from expert photographers.',
    location: 'Nature Park, CO',
    date: DateTime.now().add(const Duration(days: 9)),
    imageUrl: 'https://images.unsplash.com/photo-1542038784456-1ea8e935640e?w=800&q=80',
    price: 65.00,
    category: 'Art',
    organizer: 'Lens Masters',
  ),
  Event(
    id: '15',
    title: 'Rooftop Yoga Session',
    description: 'Start your morning with a relaxing yoga session with breathtaking city views.',
    location: 'Skyline Terrace, NY',
    date: DateTime.now().add(const Duration(days: 6)),
    imageUrl: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800&q=80',
    price: 20.00,
    category: 'Sports',
    organizer: 'Zen Space',
  ),
];
