-- CLEAN START: Remove existing tables and triggers if they exist
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
DROP FUNCTION IF EXISTS public.handle_new_user();
DROP TABLE IF EXISTS notifications CASCADE;
DROP TABLE IF EXISTS fines CASCADE;
DROP TABLE IF EXISTS attendance CASCADE;
DROP TABLE IF EXISTS reservations CASCADE;
DROP TABLE IF EXISTS seats CASCADE;
DROP TABLE IF EXISTS software_house_settings CASCADE;
DROP TABLE IF EXISTS profiles CASCADE;

-- 1. PROFILES TABLE
CREATE TABLE profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  full_name TEXT,
  email TEXT UNIQUE,
  phone TEXT,
  student_id TEXT,
  course TEXT,
  profile_image TEXT,
  role TEXT DEFAULT 'student', -- 'student' or 'admin'
  status TEXT DEFAULT 'pending', -- 'pending', 'approved', 'rejected'
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. SOFTWARE HOUSE SETTINGS
CREATE TABLE software_house_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  house_name TEXT DEFAULT 'SeatSync',
  total_seats INT DEFAULT 30,
  reservation_deadline TIME DEFAULT '10:00:00',
  fine_amount DECIMAL DEFAULT 200,
  opening_time TIME DEFAULT '09:00:00',
  closing_time TIME DEFAULT '18:00:00',
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

INSERT INTO software_house_settings (house_name, total_seats, reservation_deadline, fine_amount, opening_time, closing_time)
VALUES ('SeatSync', 30, '10:00:00', 200, '09:00:00', '18:00:00');

-- 3. SEATS TABLE
CREATE TABLE seats (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  seat_number TEXT UNIQUE NOT NULL,
  status TEXT DEFAULT 'available',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Insert 30 seats
DO $$
BEGIN
    FOR i IN 1..30 LOOP
        INSERT INTO seats (seat_number) VALUES ('Seat ' || LPAD(i::text, 2, '0'));
    END LOOP;
END $$;

-- 4. RESERVATIONS TABLE
CREATE TABLE reservations (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  student_id UUID REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,
  seat_id BIGINT REFERENCES seats(id) ON DELETE CASCADE NOT NULL,
  reservation_date DATE DEFAULT CURRENT_DATE NOT NULL,
  reserved_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  status TEXT DEFAULT 'reserved',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(student_id, reservation_date),
  UNIQUE(seat_id, reservation_date)
);

-- 5. FINES TABLE
CREATE TABLE fines (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  student_id UUID REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,
  reservation_id UUID REFERENCES reservations(id) ON DELETE SET NULL,
  amount DECIMAL NOT NULL,
  reason TEXT NOT NULL,
  status TEXT DEFAULT 'unpaid',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  paid_at TIMESTAMP WITH TIME ZONE
);

-- 6. NOTIFICATIONS TABLE
CREATE TABLE notifications (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,
  title TEXT NOT NULL,
  message TEXT NOT NULL,
  is_read BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 7. AUTH TRIGGER FOR AUTOMATIC PROFILE CREATION
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, email, phone, student_id, course, role, status)
  VALUES (
    new.id,
    new.raw_user_meta_data->>'full_name',
    new.email,
    new.raw_user_meta_data->>'phone',
    new.raw_user_meta_data->>'student_id',
    new.raw_user_meta_data->>'course',
    COALESCE(new.raw_user_meta_data->>'role', 'student'),
    COALESCE(new.raw_user_meta_data->>'status', 'pending')
  );
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- 8. ROW LEVEL SECURITY (RLS) POLICIES
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE software_house_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE seats ENABLE ROW LEVEL SECURITY;
ALTER TABLE reservations ENABLE ROW LEVEL SECURITY;
ALTER TABLE fines ENABLE ROW LEVEL SECURITY;
ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;

-- Profiles Policies
CREATE POLICY "Public profiles are viewable by everyone." ON profiles FOR SELECT USING (true);
CREATE POLICY "Users can update own profile." ON profiles FOR UPDATE USING (auth.uid() = id);

-- Settings Policies
CREATE POLICY "Settings are viewable by everyone." ON software_house_settings FOR SELECT USING (true);
CREATE POLICY "Only admins can update settings." ON software_house_settings FOR UPDATE USING (
  EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
);

-- Seats Policies
CREATE POLICY "Seats are viewable by everyone." ON seats FOR SELECT USING (true);

-- Reservations Policies
CREATE POLICY "Users can view own reservations." ON reservations FOR SELECT USING (auth.uid() = student_id);
CREATE POLICY "Users can insert own reservations." ON reservations FOR INSERT WITH CHECK (auth.uid() = student_id);
CREATE POLICY "Admins can view all reservations." ON reservations FOR SELECT USING (
  EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
);
CREATE POLICY "Admins can update all reservations." ON reservations FOR UPDATE USING (
  EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
);

-- Fines Policies
CREATE POLICY "Users can view own fines." ON fines FOR SELECT USING (auth.uid() = student_id);
CREATE POLICY "Admins can manage all fines." ON fines FOR ALL USING (
  EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
);
